# Generated by Django 4.1.4 on 2022-12-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_visit_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
